"""add verify for user

Revision ID: f09ab1044d37
Revises: 
Create Date: 2024-01-08 14:22:09.571575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f09ab1044d37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('birthday', sa.String(length=30), nullable=True))
    op.add_column('contacts', sa.Column('data', sa.NullType(), nullable=True))
    op.add_column('contacts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('contacts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('contacts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('contacts', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('contacts', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('contacts', 'phone',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.drop_index('ix_contacts_email', table_name='contacts')
    op.drop_index('ix_contacts_id', table_name='contacts')
    op.drop_index('ix_contacts_phone', table_name='contacts')
    op.create_index(op.f('ix_contacts_last_name'), 'contacts', ['last_name'], unique=True)
    op.create_foreign_key(None, 'contacts', 'users', ['user_id'], ['id'])
    op.drop_column('contacts', 'born_date')
    op.drop_column('contacts', 'description')
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    op.add_column('contacts', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('born_date', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_index(op.f('ix_contacts_last_name'), table_name='contacts')
    op.create_index('ix_contacts_phone', 'contacts', ['phone'], unique=False)
    op.create_index('ix_contacts_id', 'contacts', ['id'], unique=False)
    op.create_index('ix_contacts_email', 'contacts', ['email'], unique=True)
    op.alter_column('contacts', 'phone',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('contacts', 'last_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('contacts', 'first_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('contacts', 'user_id')
    op.drop_column('contacts', 'updated_at')
    op.drop_column('contacts', 'created_at')
    op.drop_column('contacts', 'data')
    op.drop_column('contacts', 'birthday')
    # ### end Alembic commands ###
